import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./Providers";
import Sidebar from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex`}
      >
        <nav className="w-20 bg-gray-900 flex flex-col items-center py-4 space-y-4 overflow-y-auto">
          {/* サーバーアイコンの例 */}
          <button
            className="w-12 h-12 bg-blue-500 rounded-full hover:bg-blue-700"
            title="Server 1"
          />
          <button
            className="w-12 h-12 bg-green-500 rounded-full hover:bg-green-700"
            title="Server 2"
          />
          <button
            className="w-12 h-12 bg-red-500 rounded-full hover:bg-red-700"
            title="Server 3"
          />
        </nav>
        <Sidebar />

        <ReduxProvider>
          <main className="flex-1 overflow-auto">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
