import type { Metadata } from "next";

import "./globals.css";
import AppLayout from "@components/templates/AppLayout";
import ReduxProvider from "@store/ReduxProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
