import type { Metadata } from "next";

import "./globals.css";
import AppLayout from "@components/templates/AppLayout";
import ReduxProvider from "@store/ReduxProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <AppLayout>
        <main className="flex-1 overflow-auto">{children}</main>
      </AppLayout>
    </ReduxProvider>
  );
}
